name=IoTW_LMIC
version=1.0.0
author=k.gollmer
maintainer=IoT-Werkstatt
sentence=setup LoRa LMIC for iot-werkstatt
paragraph=event handling, deepsleep, save structures to RTC
category=Signal Input/Output
url=https://iot-werkstatt.de
architectures=esp8266,esp32
