name=IoTW_SmartServo
version=1.0.0
author=k.gollmer
maintainer=IoT-Werkstatt
sentence=wrapper Smart Servos for iot-werkstatt
paragraph=for esp32
category=Signal Input/Output
url=https://iot-werkstatt.de
architectures=esp32, esp8266
depends=
