name=IoTW_PlayTone
version=1.0.0
author=k.gollmer
maintainer=IoT-Werkstatt
sentence=tone generation for iot-werkstatt
paragraph=tone fpr esp32
category=Signal Input/Output
url=https://iot-werkstatt.de
architectures=esp32
depends=
