name=IoTW_Sniffer
version=1.0.0
author=IoT-Werkstatt
maintainer=IoT-Werkstatt
sentence=wrapper for paxcounter and wifi-sniffer
paragraph=wrapper for paxcounter and wifi-sniffer
category=Signal Input/Output
url=https://iot-werkstatt.de
architectures=esp8266,esp32
