name=IoTW_EI
version=1.0.0
author=Martin Seidinger, Nicolas Kiebel, Robin Barton, Klaus Gollmer
maintainer=IoT-Werkstatt
sentence=setup EdgeImpulse for iot-werkstatt
paragraph=save samples to EI-cloud
category=Signal Input/Output
url=https://iot-werkstatt.de
architectures=esp8266,esp32
